// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'kitchen_service.dart';

class RecipeCatalogue {
  static final List<Recipe> allRecipes = [
    // --- Starting / Common (Sophistication 0.0 - 1.5) ---
    Recipe(
      id: 'staple_bread',
      name: 'Spelt Bread',
      ingredients: {'flour_spelt': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 60,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'hard_hardtack',
      name: 'Hardtack',
      ingredients: {'flour': 1, 'salt': 2},
      sophistication: 0.5,
      yield: 5,
      baseQuality: 0.5,
      durationMinutes: 60,
      minKnifeSkills: 0,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'protein_mistery_stew',
      name: 'Stew of Unknown Protein',
      ingredients: {'meat': 1, 'potato': 1, 'salt': 1},
      sophistication: 0.8,
      yield: 4,
      baseQuality: 0.8,
      durationMinutes: 60,
      minKnifeSkills: 10,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'fried_generic_meat',
      name: 'Sizzling Generic Protein',
      ingredients: {'meat': 1, 'pepper': 1},
      sophistication: 0.9,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'boiled_cabbage',
      name: 'Boiled Cabbage',
      ingredients: {'cabbage': 1, 'salt': 1},
      sophistication: 0.6,
      yield: 2,
      baseQuality: 0.7,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'roasted_rat',
      name: 'Roasted Rat on a Stick',
      ingredients: {'meat_rat': 1, 'salt': 1},
      sophistication: 0.2,
      yield: 1,
      baseQuality: 0.3,
      durationMinutes: 20,
      minKnifeSkills: 5,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'porridge',
      name: 'Simple Porridge',
      ingredients: {'grain': 2},
      sophistication: 0.4,
      yield: 3,
      baseQuality: 0.8,
      durationMinutes: 20,
      minKnifeSkills: 0,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'scrambled_eggs',
      name: 'Scrambled Eggs',
      ingredients: {'eggs': 2, 'butter': 1, 'salt': 1},
      sophistication: 1.2,
      yield: 2,
      baseQuality: 1.0,
      durationMinutes: 10,
      minKnifeSkills: 0,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'roasted_carrots',
      name: 'Roasted Carrots',
      ingredients: {'carrots': 1, 'honey': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'baked_apple',
      name: 'Baked Apple',
      ingredients: {'apple': 1, 'cinnamon': 1},
      sophistication: 1.0,
      yield: 1,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 0,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'simple_pears',
      name: 'Simple Pears',
      ingredients: {'pear': 1, 'sugar': 1},
      sophistication: 1.0,
      yield: 1,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 0,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'berry_mush',
      name: 'Berry Mush',
      ingredients: {'berry': 1, 'honey': 1},
      sophistication: 1.0,
      yield: 1,
      baseQuality: 0.9,
      durationMinutes: 15,
      minKnifeSkills: 0,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'rice_porridge',
      name: 'Rice Porridge',
      ingredients: {'rice': 1, 'milk': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 0,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'boiled_beets',
      name: 'Boiled Beets',
      ingredients: {'beets': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 45,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'cucumber_slices',
      name: 'Cucumber Slices',
      ingredients: {'cucumber': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 1,
      baseQuality: 0.9,
      durationMinutes: 10,
      minKnifeSkills: 5,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'roasted_squash',
      name: 'Roasted Squash',
      ingredients: {'squash': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 45,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'cabbage_soup_simple',
      name: 'Simple Cabbage Soup',
      ingredients: {'cabbage': 1, 'onion': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 4,
      baseQuality: 0.9,
      durationMinutes: 45,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'beans_on_toast',
      name: 'Beans on Toast',
      ingredients: {'beans': 1, 'flour_spelt': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),

    Recipe(
      id: 'cucumber_cabbage_slaw',
      name: 'Cucumber and Cabbage Slaw',
      ingredients: {'cucumber': 1, 'cabbage': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 4,
      baseQuality: 0.9,
      durationMinutes: 15,
      minKnifeSkills: 10,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'rice_beans_simple',
      name: 'Simmered Rice and Beans',
      ingredients: {'rice': 1, 'beans': 1, 'paprika': 1},
      sophistication: 1.0,
      yield: 3,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),

    Recipe(
      id: 'berry_rice_porridge',
      name: 'Sweet Berry Rice Porridge',
      ingredients: {'rice': 1, 'berry': 1, 'milk': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 0,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'squash_cabbage_soup',
      name: 'Rustic Squash & Cabbage Soup',
      ingredients: {'squash': 1, 'cabbage': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 4,
      baseQuality: 0.9,
      durationMinutes: 45,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),

    // --- Low / Standard (Sophistication 1.5 - 2.5) ---
    Recipe(
      id: 'omelette',
      name: 'Country Omelette',
      ingredients: {'eggs': 2, 'salt': 1},
      sophistication: 1.8,
      yield: 5,
      baseQuality: 1.2,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'mashed_potatoes',
      name: 'Mashed Potatoes',
      ingredients: {'potato': 2, 'butter': 1, 'salt': 1},
      sophistication: 1.5,
      yield: 4,
      baseQuality: 1.1,
      durationMinutes: 30,
      minKnifeSkills: 10,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'baked_potato',
      name: 'Baked Potato',
      ingredients: {'potato': 1, 'salt': 1},
      sophistication: 1.2,
      yield: 1,
      baseQuality: 1.0,
      durationMinutes: 45,
      minKnifeSkills: 0,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'bean_stew',
      name: 'Faba & Green Bean Stew',
      ingredients: {'faba_beans': 1, 'green_beans': 1, 'salt': 1},
      sophistication: 2.1,
      yield: 4,
      baseQuality: 1.0,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'roast_chicken',
      name: 'Herbed Roast Chicken',
      ingredients: {'meat_chicken': 1, 'salt': 1, 'pepper': 1},
      sophistication: 2.3,
      yield: 4,
      baseQuality: 1.3,
      durationMinutes: 120,
      minKnifeSkills: 25,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'chicken_soup',
      name: 'Chicken Soup',
      ingredients: {'meat_chicken': 1, 'carrots': 1, 'onion': 1, 'salt': 1},
      sophistication: 2.2,
      yield: 5,
      baseQuality: 1.4,
      durationMinutes: 90,
      minKnifeSkills: 15,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'vegetable_stew',
      name: 'Root Vegetable Stew',
      ingredients: {'potato': 1, 'carrots': 1, 'onion': 1, 'salt': 1},
      sophistication: 1.9,
      yield: 5,
      baseQuality: 1.1,
      durationMinutes: 60,
      minKnifeSkills: 15,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'grilled_fish',
      name: 'Grilled River Fish',
      ingredients: {'fish': 1, 'salt': 1, 'lemon': 1},
      sophistication: 2.0,
      yield: 2,
      baseQuality: 1.3,
      durationMinutes: 20,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'pork_chops',
      name: 'Pan-seared Pork Chops',
      ingredients: {'meat_pork': 1, 'salt': 1, 'pepper': 1, 'butter': 1},
      sophistication: 2.4,
      yield: 2,
      baseQuality: 1.4,
      durationMinutes: 25,
      minKnifeSkills: 10,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'sausage_links',
      name: 'Smoked Sausage Links',
      ingredients: {'meat_pork': 1, 'pepper': 1, 'salt': 1, 'paprika': 1},
      sophistication: 2.2,
      yield: 6,
      baseQuality: 1.2,
      durationMinutes: 180,
      minKnifeSkills: 30,
      minFireSkills: 15,
    ),

    Recipe(
      id: 'apple_pear_salad',
      name: 'Apple and Pear Salad',
      ingredients: {'apple': 1, 'pear': 1, 'honey': 1},
      sophistication: 1.8,
      yield: 2,
      baseQuality: 1.1,
      durationMinutes: 15,
      minKnifeSkills: 10,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'cucumber_salad',
      name: 'Cucumber Salad',
      ingredients: {'cucumber': 1, 'onion': 1, 'dill': 1},
      sophistication: 1.6,
      yield: 2,
      baseQuality: 1.0,
      durationMinutes: 15,
      minKnifeSkills: 10,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'beet_salad_simple',
      name: 'Beet and Apple Salad',
      ingredients: {'beets': 1, 'apple': 1, 'salt': 1},
      sophistication: 1.7,
      yield: 2,
      baseQuality: 1.0,
      durationMinutes: 20,
      minKnifeSkills: 15,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'squash_soup_simple',
      name: 'Cream of Squash Soup',
      ingredients: {'squash': 1, 'onion': 1, 'cream': 1},
      sophistication: 2.1,
      yield: 4,
      baseQuality: 1.2,
      durationMinutes: 45,
      minKnifeSkills: 15,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'rice_pudding_simple',
      name: 'Simple Rice Pudding',
      ingredients: {'rice': 1, 'milk': 1, 'cinnamon': 1},
      sophistication: 1.9,
      yield: 3,
      baseQuality: 1.2,
      durationMinutes: 30,
      minKnifeSkills: 0,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'chicken_rice_simple',
      name: 'Warm Chicken and Rice',
      ingredients: {'meat_chicken': 1, 'rice': 1, 'salt': 1},
      sophistication: 1.8,
      yield: 3,
      baseQuality: 1.1,
      durationMinutes: 45,
      minKnifeSkills: 10,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'beef_stew_basic',
      name: 'Basic Beef Stew',
      ingredients: {'meat_beef': 1, 'potato': 1, 'onion': 1},
      sophistication: 2.0,
      yield: 4,
      baseQuality: 1.2,
      durationMinutes: 90,
      minKnifeSkills: 15,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'pork_cabbage_bake',
      name: 'Pork and Cabbage Bake',
      ingredients: {'meat_pork': 1, 'cabbage': 1, 'paprika': 1},
      sophistication: 2.2,
      yield: 3,
      baseQuality: 1.2,
      durationMinutes: 60,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'lamb_skewers_cumin',
      name: 'Cumin Lamb Skewers',
      ingredients: {'meat_lamb': 1, 'garlic': 1, 'cumin': 1},
      sophistication: 2.3,
      yield: 2,
      baseQuality: 1.3,
      durationMinutes: 30,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'mushroom_saute_butter',
      name: 'Butter-Sautéed Mushrooms',
      ingredients: {'mushrooms': 1, 'butter': 1, 'garlic': 1},
      sophistication: 2.1,
      yield: 2,
      baseQuality: 1.3,
      durationMinutes: 20,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),

    Recipe(
      id: 'apple_pear_berry_salad',
      name: 'Orchard Fruit Salad',
      ingredients: {'apple': 1, 'pear': 1, 'berry': 1},
      sophistication: 1.8,
      yield: 3,
      baseQuality: 1.2,
      durationMinutes: 15,
      minKnifeSkills: 15,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'beet_squash_roast_simple',
      name: 'Roasted Beet and Squash',
      ingredients: {'beets': 1, 'squash': 1, 'butter': 1},
      sophistication: 2.1,
      yield: 3,
      baseQuality: 1.2,
      durationMinutes: 45,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),

    Recipe(
      id: 'apple_berry_crisp',
      name: 'Apple and Berry Crisp',
      ingredients: {'apple': 1, 'berry': 1, 'sugar': 1},
      sophistication: 2.1,
      yield: 4,
      baseQuality: 1.2,
      durationMinutes: 45,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'pear_cucumber_salad_light',
      name: 'Light Pear & Cucumber Salad',
      ingredients: {'pear': 1, 'cucumber': 1, 'honey': 1},
      sophistication: 1.8,
      yield: 2,
      baseQuality: 1.1,
      durationMinutes: 15,
      minKnifeSkills: 15,
      minFireSkills: 0,
    ),

    Recipe(
      id: 'cucumber_cheese_roll',
      name: 'Cucumber & Cheese Rolls',
      ingredients: {'cucumber': 1, 'cheese': 1, 'salt': 1},
      sophistication: 1.6,
      yield: 2,
      baseQuality: 1.1,
      durationMinutes: 15,
      minKnifeSkills: 10,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'cucumber_squash_salad',
      name: 'Cucumber & Squash Salad',
      ingredients: {'cucumber': 1, 'squash': 1, 'salt': 1},
      sophistication: 1.6,
      yield: 2,
      baseQuality: 1.1,
      durationMinutes: 15,
      minKnifeSkills: 10,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'pickled_cucumbers_dill',
      name: 'Pickled Cucumbers with Dill',
      ingredients: {'cucumber': 2, 'dill': 1, 'honey': 1},
      sophistication: 1.7,
      yield: 2,
      baseQuality: 1.2,
      durationMinutes: 30,
      minKnifeSkills: 10,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'squash_bean_casserole',
      name: 'Squash & Bean Casserole',
      ingredients: {'squash': 1, 'beans': 1, 'butter': 1},
      sophistication: 2.1,
      yield: 4,
      baseQuality: 1.3,
      durationMinutes: 45,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'beet_cabbage_soup_simple',
      name: 'Simple Beet & Cabbage Soup',
      ingredients: {'beets': 1, 'cabbage': 1, 'salt': 1},
      sophistication: 1.9,
      yield: 4,
      baseQuality: 1.2,
      durationMinutes: 45,
      minKnifeSkills: 15,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'beans_cabbage_stir_fry',
      name: 'Beans & Cabbage Stir-Fry',
      ingredients: {'beans': 1, 'cabbage': 1, 'paprika': 1},
      sophistication: 2.0,
      yield: 3,
      baseQuality: 1.2,
      durationMinutes: 30,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'rice_cucumber_refresh',
      name: 'Chilled Rice & Cucumber Bowl',
      ingredients: {'rice': 1, 'cucumber': 1, 'dill': 1},
      sophistication: 1.8,
      yield: 2,
      baseQuality: 1.1,
      durationMinutes: 20,
      minKnifeSkills: 10,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'duck_cabbage_roast_simple',
      name: 'Roast Duck with Cabbage',
      ingredients: {'meat_duck': 1, 'cabbage': 1, 'salt': 1},
      sophistication: 2.3,
      yield: 3,
      baseQuality: 1.3,
      durationMinutes: 60,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'lamb_beet_salad_warm',
      name: 'Warm Lamb & Beet Salad',
      ingredients: {'meat_lamb': 1, 'beets': 1, 'salt': 1},
      sophistication: 2.4,
      yield: 3,
      baseQuality: 1.4,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'pork_squash_puree_simple',
      name: 'Pork Chops with Squash Purée',
      ingredients: {'meat_pork': 1, 'squash': 1, 'butter': 1},
      sophistication: 2.5,
      yield: 3,
      baseQuality: 1.4,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),

    Recipe(
      id: 'squash_cheese_melt',
      name: 'Baked Squash & Cheese',
      ingredients: {'squash': 1, 'cheese': 1, 'butter': 1},
      sophistication: 2.2,
      yield: 3,
      baseQuality: 1.3,
      durationMinutes: 45,
      minKnifeSkills: 10,
      minFireSkills: 20,
    ),

    // --- Standard / High (Sophistication 2.5 - 3.5) ---
    Recipe(
      id: 'beef_root_stew',
      name: 'Beef & Root Stew',
      ingredients: {'meat_beef': 10, 'potato': 1, 'carrots': 1, 'beets': 1},
      sophistication: 2.6,
      yield: 6,
      baseQuality: 1.4,
      durationMinutes: 150,
      minKnifeSkills: 30,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'durum_pasta',
      name: 'Fresh Durum Pasta',
      ingredients: {'flour_durum': 1, 'eggs': 2},
      sophistication: 2.7,
      yield: 3,
      baseQuality: 1.1,
      durationMinutes: 90,
      minKnifeSkills: 15,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'spaghetti_carbonara',
      name: 'Spaghetti Carbonara',
      ingredients: {'flour_durum': 1, 'eggs': 1, 'cheese': 1, 'meat_pork': 1},
      sophistication: 3.2,
      yield: 3,
      baseQuality: 1.8,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'shepherds_pie',
      name: 'Shepherd\'s Pie',
      ingredients: {'meat_beef': 1, 'carrots': 1, 'onion': 1, 'potato': 1},
      sophistication: 2.8,
      yield: 6,
      baseQuality: 1.6,
      durationMinutes: 90,
      minKnifeSkills: 25,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'potato_dauphinoise',
      name: 'Potato Dauphinoise',
      ingredients: {'potato': 1, 'cream': 1, 'cheese': 1, 'salt': 1},
      sophistication: 3.1,
      yield: 4,
      baseQuality: 1.7,
      durationMinutes: 80,
      minKnifeSkills: 30,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'tartiflette',
      name: 'Tartiflette',
      ingredients: {'cheese': 1, 'potato': 1, 'meat_pork': 1, 'onion': 1},
      sophistication: 3.3,
      yield: 6,
      baseQuality: 1.8,
      durationMinutes: 70,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'gnocchi',
      name: 'Potato Gnocchi',
      ingredients: {'potato': 1, 'flour': 1, 'salt': 1, 'eggs': 1},
      sophistication: 2.9,
      yield: 4,
      baseQuality: 1.5,
      durationMinutes: 60,
      minKnifeSkills: 25,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'latkes',
      name: 'Potato Latkes',
      ingredients: {'potato': 1, 'onion': 1, 'salt': 1, 'eggs': 1},
      sophistication: 2.7,
      yield: 4,
      baseQuality: 1.4,
      durationMinutes: 40,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'mushroom_risotto',
      name: 'Mushroom Risotto',
      ingredients: {'rice': 1, 'mushrooms': 1, 'onion': 1, 'cheese': 1},
      sophistication: 3.4,
      yield: 4,
      baseQuality: 1.9,
      durationMinutes: 50,
      minKnifeSkills: 25,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'stuffed_peppers',
      name: 'Stuffed Peppers',
      ingredients: {'peppers': 1, 'meat_beef': 1, 'rice': 1, 'onion': 1},
      sophistication: 2.9,
      yield: 4,
      baseQuality: 1.6,
      durationMinutes: 65,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'fish_and_chips',
      name: 'Fish and Chips',
      ingredients: {'fish': 1, 'potato': 1, 'flour': 1, 'salt': 1},
      sophistication: 2.6,
      yield: 3,
      baseQuality: 1.5,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),

    Recipe(
      id: 'apple_pie_classic',
      name: 'Classic Apple Pie',
      ingredients: {'apple': 2, 'flour_spelt': 1, 'butter': 1, 'sugar': 1},
      sophistication: 2.8,
      yield: 6,
      baseQuality: 1.4,
      durationMinutes: 90,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'pear_tart_rustic',
      name: 'Rustic Pear Tart',
      ingredients: {'pear': 2, 'flour_spelt': 1, 'butter': 1, 'sugar': 1},
      sophistication: 2.7,
      yield: 6,
      baseQuality: 1.4,
      durationMinutes: 75,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'berry_pie_wild',
      name: 'Wild Berry Pie',
      ingredients: {'berry': 2, 'flour_spelt': 1, 'butter': 1, 'sugar': 1},
      sophistication: 2.8,
      yield: 6,
      baseQuality: 1.4,
      durationMinutes: 90,
      minKnifeSkills: 15,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'duck_pot_pie',
      name: 'Duck and Potato Pie',
      ingredients: {'meat_duck': 1, 'potato': 1, 'flour_spelt': 1, 'butter': 1},
      sophistication: 3.2,
      yield: 4,
      baseQuality: 1.6,
      durationMinutes: 120,
      minKnifeSkills: 25,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'lamb_stew_hearty',
      name: 'Hearty Lamb Stew',
      ingredients: {'meat_lamb': 1, 'potato': 2, 'carrots': 1, 'onion': 1},
      sophistication: 2.9,
      yield: 6,
      baseQuality: 1.5,
      durationMinutes: 120,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'beef_stroganoff_basic',
      name: 'Beef Stroganoff',
      ingredients: {'meat_beef': 1, 'mushrooms': 1, 'cream': 1, 'onion': 1},
      sophistication: 3.1,
      yield: 4,
      baseQuality: 1.6,
      durationMinutes: 45,
      minKnifeSkills: 25,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'pork_chops_apples_roast',
      name: 'Roast Pork with Apples',
      ingredients: {'meat_pork': 1, 'apple': 2, 'butter': 1, 'salt': 1},
      sophistication: 3.0,
      yield: 3,
      baseQuality: 1.5,
      durationMinutes: 60,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'mushroom_soup_creamy',
      name: 'Creamy Mushroom Soup',
      ingredients: {'mushrooms': 2, 'onion': 1, 'cream': 1, 'butter': 1},
      sophistication: 2.9,
      yield: 4,
      baseQuality: 1.4,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'cabbage_rolls_stuffed',
      name: 'Stuffed Cabbage Rolls',
      ingredients: {'cabbage': 1, 'meat_beef': 1, 'rice': 1, 'onion': 1},
      sophistication: 3.2,
      yield: 6,
      baseQuality: 1.5,
      durationMinutes: 90,
      minKnifeSkills: 25,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'vegetable_risotto_spring',
      name: 'Spring Vegetable Risotto',
      ingredients: {'rice': 1, 'cucumber': 1, 'squash': 1, 'cheese': 1},
      sophistication: 3.3,
      yield: 4,
      baseQuality: 1.6,
      durationMinutes: 45,
      minKnifeSkills: 25,
      minFireSkills: 30,
    ),

    Recipe(
      id: 'pork_squash_bake_sage',
      name: 'Savory Pork & Squash Bake',
      ingredients: {'meat_pork': 1, 'squash': 1, 'butter': 1},
      sophistication: 2.8,
      yield: 4,
      baseQuality: 1.5,
      durationMinutes: 75,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'cabbage_soup_rich_broth',
      name: 'Rich Cabbage Stew',
      ingredients: {'cabbage': 1, 'potato': 1, 'carrots': 1, 'onion': 1},
      sophistication: 2.7,
      yield: 6,
      baseQuality: 1.4,
      durationMinutes: 90,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),

    Recipe(
      id: 'squash_apple_soup_rich',
      name: 'Rich Squash & Apple Soup',
      ingredients: {'squash': 1, 'apple': 1, 'cream': 1, 'butter': 1},
      sophistication: 2.9,
      yield: 4,
      baseQuality: 1.4,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'pork_apple_squash_bake_fancy',
      name: 'Pork, Apple & Squash Bake',
      ingredients: {'meat_pork': 1, 'apple': 1, 'squash': 1, 'butter': 1},
      sophistication: 3.1,
      yield: 4,
      baseQuality: 1.6,
      durationMinutes: 75,
      minKnifeSkills: 25,
      minFireSkills: 25,
    ),

    // --- High Sophistication (3.5 - 4.5) ---
    Recipe(
      id: 'fondant_potatoes',
      name: 'Fondant Potatoes',
      ingredients: {'potato': 1, 'butter': 1, 'meat': 1, 'garlic': 1},
      sophistication: 3.8,
      yield: 4,
      baseQuality: 2.2,
      durationMinutes: 50,
      minKnifeSkills: 35,
      minFireSkills: 40,
    ),
    Recipe(
      id: 'beef_bourguignon',
      name: 'Beef Bourguignon',
      ingredients: {'meat_beef': 1, 'wine': 1, 'mushrooms': 1, 'onion': 1},
      sophistication: 4.2,
      yield: 6,
      baseQuality: 2.5,
      durationMinutes: 240,
      minKnifeSkills: 30,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'coq_au_vin',
      name: 'Coq au Vin',
      ingredients: {'meat_chicken': 1, 'wine': 1, 'mushrooms': 1, 'onion': 1},
      sophistication: 4.1,
      yield: 5,
      baseQuality: 2.4,
      durationMinutes: 180,
      minKnifeSkills: 25,
      minFireSkills: 40,
    ),
    Recipe(
      id: 'chocolate_delight',
      name: 'Chocolate Ganache',
      ingredients: {'chocolate': 1, 'sugar': 1, 'milk': 1},
      sophistication: 3.9,
      yield: 2,
      baseQuality: 2.5,
      durationMinutes: 60,
      minKnifeSkills: 20,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'morning_ritual',
      name: 'Coffee Blend',
      ingredients: {'coffee': 1, 'sugar': 1},
      sophistication: 3.5,
      yield: 1,
      baseQuality: 1.8,
      durationMinutes: 10,
      minKnifeSkills: 5,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'roast_duck',
      name: 'Crispy Roast Duck',
      ingredients: {'meat_duck': 1, 'salt': 1, 'honey': 1, 'pepper': 1},
      sophistication: 4.0,
      yield: 4,
      baseQuality: 2.3,
      durationMinutes: 150,
      minKnifeSkills: 30,
      minFireSkills: 35,
    ),
    Recipe(
      id: 'rack_of_lamb',
      name: 'Herb-Crusted Rack of Lamb',
      ingredients: {'meat_lamb': 1, 'pepper': 1, 'garlic': 1, 'mustard': 1},
      sophistication: 4.3,
      yield: 4,
      baseQuality: 2.6,
      durationMinutes: 45,
      minKnifeSkills: 35,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'scallop_ceviche',
      name: 'Scallop Ceviche',
      ingredients: {'scallops': 1, 'lemon': 1, 'onion': 1, 'salt': 1},
      sophistication: 3.7,
      yield: 2,
      baseQuality: 2.1,
      durationMinutes: 20,
      minKnifeSkills: 40,
      minFireSkills: 0,
    ),

    Recipe(
      id: 'duck_confit_classic',
      name: 'Duck Confit',
      ingredients: {'meat_duck': 1, 'salt': 1, 'garlic': 1, 'pepper': 1},
      sophistication: 4.2,
      yield: 2,
      baseQuality: 2.5,
      durationMinutes: 240,
      minKnifeSkills: 35,
      minFireSkills: 40,
    ),
    Recipe(
      id: 'lamb_shank_braised',
      name: 'Braised Lamb Shank',
      ingredients: {'meat_lamb': 1, 'garlic': 1, 'wine': 1, 'onion': 1},
      sophistication: 4.3,
      yield: 2,
      baseQuality: 2.6,
      durationMinutes: 180,
      minKnifeSkills: 35,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'beef_ragout_rich',
      name: 'Rich Beef Ragout',
      ingredients: {'meat_beef': 1, 'onion': 1, 'carrots': 1, 'wine': 1},
      sophistication: 4.1,
      yield: 4,
      baseQuality: 2.4,
      durationMinutes: 150,
      minKnifeSkills: 30,
      minFireSkills: 40,
    ),
    Recipe(
      id: 'pear_cheese_plate',
      name: 'Pear & Cheese Plate',
      ingredients: {'pear': 1, 'cheese': 1, 'honey': 1},
      sophistication: 3.6,
      yield: 2,
      baseQuality: 2.2,
      durationMinutes: 15,
      minKnifeSkills: 30,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'beet_risotto_fancy',
      name: 'Beetroot Risotto',
      ingredients: {'beets': 1, 'rice': 1, 'cheese': 1, 'butter': 1},
      sophistication: 3.9,
      yield: 4,
      baseQuality: 2.3,
      durationMinutes: 45,
      minKnifeSkills: 25,
      minFireSkills: 35,
    ),
    Recipe(
      id: 'squash_risotto_fancy',
      name: 'Butternut Squash Risotto',
      ingredients: {'squash': 1, 'rice': 1, 'cheese': 1, 'butter': 1},
      sophistication: 4.0,
      yield: 4,
      baseQuality: 2.4,
      durationMinutes: 45,
      minKnifeSkills: 25,
      minFireSkills: 35,
    ),
    Recipe(
      id: 'cucumber_gazpacho_cold',
      name: 'Chilled Cucumber Gazpacho',
      ingredients: {'cucumber': 2, 'onion': 1, 'garlic': 1, 'salt': 1},
      sophistication: 3.7,
      yield: 4,
      baseQuality: 2.1,
      durationMinutes: 30,
      minKnifeSkills: 35,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'berry_tart_glaze',
      name: 'Glazed Berry Tart',
      ingredients: {'berry': 2, 'flour_durum': 1, 'cream': 1, 'sugar': 1},
      sophistication: 4.1,
      yield: 6,
      baseQuality: 2.3,
      durationMinutes: 60,
      minKnifeSkills: 30,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'apple_strudel_traditional',
      name: 'Traditional Apple Strudel',
      ingredients: {'apple': 2, 'flour_spelt': 1, 'butter': 1, 'cinnamon': 1},
      sophistication: 4.2,
      yield: 8,
      baseQuality: 2.4,
      durationMinutes: 90,
      minKnifeSkills: 35,
      minFireSkills: 35,
    ),

    Recipe(
      id: 'lamb_apple_stew_rich',
      name: 'Rich Lamb & Apple Stew',
      ingredients: {'meat_lamb': 1, 'apple': 1, 'onion': 1, 'garlic': 1},
      sophistication: 4.1,
      yield: 4,
      baseQuality: 2.4,
      durationMinutes: 120,
      minKnifeSkills: 30,
      minFireSkills: 40,
    ),
    Recipe(
      id: 'duck_berry_reduction_glaze',
      name: 'Duck with Berry Reduction',
      ingredients: {'meat_duck': 1, 'berry': 2, 'honey': 1, 'wine': 1},
      sophistication: 4.3,
      yield: 2,
      baseQuality: 2.6,
      durationMinutes: 60,
      minKnifeSkills: 35,
      minFireSkills: 45,
    ),

    Recipe(
      id: 'duck_pear_berry_sauce_glaze',
      name: 'Duck with Pear & Berry Sauce',
      ingredients: {'meat_duck': 1, 'pear': 1, 'berry': 1, 'wine': 1},
      sophistication: 4.4,
      yield: 2,
      baseQuality: 2.7,
      durationMinutes: 60,
      minKnifeSkills: 35,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'berry_pear_galette_fancy',
      name: 'Berry and Pear Galette',
      ingredients: {'berry': 1, 'pear': 1, 'flour_durum': 1, 'butter': 1},
      sophistication: 4.1,
      yield: 6,
      baseQuality: 2.3,
      durationMinutes: 60,
      minKnifeSkills: 30,
      minFireSkills: 30,
    ),

    // --- Exquisite (4.5 - 5.0) ---
    Recipe(
      id: 'potatoes_aligot',
      name: 'Potatoes Aligot',
      ingredients: {'potato': 1, 'butter': 2, 'cheese': 1},
      sophistication: 4.6,
      yield: 4,
      baseQuality: 3.0,
      durationMinutes: 90,
      minKnifeSkills: 30,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'beef_wellington',
      name: 'Beef Wellington',
      ingredients: {'meat_beef': 1, 'flour': 1, 'mushrooms': 1, 'wine': 1},
      sophistication: 4.9,
      yield: 5,
      baseQuality: 3.5,
      durationMinutes: 180,
      minKnifeSkills: 50,
      minFireSkills: 50,
    ),
    Recipe(
      id: 'truffle_pasta',
      name: 'Fresh Truffle Pasta',
      ingredients: {'flour_durum': 1, 'eggs': 1, 'truffles': 1, 'cheese': 1},
      sophistication: 4.8,
      yield: 3,
      baseQuality: 3.3,
      durationMinutes: 45,
      minKnifeSkills: 40,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'lobster_thermidor',
      name: 'Lobster Thermidor',
      ingredients: {'lobster': 1, 'cream': 1, 'cheese': 1, 'wine': 1},
      sophistication: 5.0,
      yield: 2,
      baseQuality: 3.8,
      durationMinutes: 90,
      minKnifeSkills: 45,
      minFireSkills: 50,
    ),
    Recipe(
      id: 'macaron_tower',
      name: 'Tower of Macarons',
      ingredients: {'almond_flour': 1, 'sugar': 1, 'eggs': 1, 'chocolate': 1},
      sophistication: 4.7,
      yield: 10,
      baseQuality: 3.2,
      durationMinutes: 120,
      minKnifeSkills: 40,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'foie_gras_terrine',
      name: 'Foie Gras Terrine',
      ingredients: {'foie_gras': 1, 'wine': 1, 'salt': 1, 'pepper': 1},
      sophistication: 4.6,
      yield: 4,
      baseQuality: 3.1,
      durationMinutes: 300,
      minKnifeSkills: 35,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'caviar_blinis',
      name: 'Caviar Blinis',
      ingredients: {'caviar': 1, 'flour': 1, 'eggs': 1, 'cream': 1},
      sophistication: 4.5,
      yield: 4,
      baseQuality: 2.9,
      durationMinutes: 40,
      minKnifeSkills: 20,
      minFireSkills: 30,
    ),

    Recipe(
      id: 'honey_glazed_duck',
      name: 'Honey-Glazed Roast Duck',
      ingredients: {'meat_duck': 1, 'honey': 1, 'garlic': 1, 'wine': 1},
      sophistication: 4.8,
      yield: 4,
      baseQuality: 3.2,
      durationMinutes: 120,
      minKnifeSkills: 40,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'lamb_herb_crust',
      name: 'Herb-Crusted Rack of Lamb',
      ingredients: {'meat_lamb': 1, 'flour_spelt': 1, 'garlic': 1, 'butter': 1},
      sophistication: 4.9,
      yield: 4,
      baseQuality: 3.4,
      durationMinutes: 90,
      minKnifeSkills: 45,
      minFireSkills: 50,
    ),
    Recipe(
      id: 'beef_carpaccio_fancy',
      name: 'Beef Carpaccio',
      ingredients: {'meat_beef': 1, 'cheese': 1, 'cucumber': 1, 'salt': 1},
      sophistication: 4.7,
      yield: 2,
      baseQuality: 3.1,
      durationMinutes: 30,
      minKnifeSkills: 50,
      minFireSkills: 0,
    ),
    Recipe(
      id: 'truffle_wild_rice',
      name: 'Wild Rice with Black Truffles',
      ingredients: {'rice': 1, 'truffles': 1, 'butter': 1, 'cheese': 1},
      sophistication: 5.0,
      yield: 3,
      baseQuality: 3.6,
      durationMinutes: 45,
      minKnifeSkills: 40,
      minFireSkills: 35,
    ),
    Recipe(
      id: 'poached_pears_honey',
      name: 'Pears Poached in Honey Wine',
      ingredients: {'pear': 2, 'wine': 1, 'honey': 1, 'cream': 1},
      sophistication: 4.6,
      yield: 4,
      baseQuality: 3.0,
      durationMinutes: 60,
      minKnifeSkills: 35,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'berry_tart_pastry_cream',
      name: 'Berry Tart with Pastry Cream',
      ingredients: {'berry': 2, 'flour_durum': 1, 'cream': 1, 'eggs': 1},
      sophistication: 4.7,
      yield: 6,
      baseQuality: 3.1,
      durationMinutes: 90,
      minKnifeSkills: 35,
      minFireSkills: 35,
    ),

    // --- Culinary Compound & Intermediate Recipes (Sophistication 2.0 - 8.5) ---
    Recipe(
      id: 'bread_dough',
      name: 'Bread Dough',
      ingredients: {'flour_spelt': 1, 'salt': 1},
      sophistication: 1.2,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'sweet_pastry_dough',
      name: 'Sweet Pastry Dough',
      ingredients: {'flour_spelt': 1, 'butter': 1, 'eggs': 1, 'sugar': 1},
      sophistication: 2.2,
      yield: 3,
      baseQuality: 1.1,
      durationMinutes: 40,
      minKnifeSkills: 15,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'sheet_pasta',
      name: 'Fresh Durum Pasta Sheets',
      ingredients: {'flour_durum': 1, 'eggs': 2},
      sophistication: 2.5,
      yield: 4,
      baseQuality: 1.1,
      durationMinutes: 40,
      minKnifeSkills: 15,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'tomato_sauce',
      name: 'Tomato Sauce',
      ingredients: {'tomato': 1, 'salt': 1, 'onion': 1},
      sophistication: 1.8,
      yield: 4,
      baseQuality: 1.0,
      durationMinutes: 30,
      minKnifeSkills: 10,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'genovese_sauce',
      name: 'Genovese Meat Sauce',
      ingredients: {'meat_beef': 1, 'meat_pork': 1, 'onion': 1, 'wine': 1},
      sophistication: 3.5,
      yield: 4,
      baseQuality: 1.5,
      durationMinutes: 120,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'baked_apple_comp',
      name: 'Baked Apple Component',
      ingredients: {'apple': 1, 'cinnamon': 1, 'sugar': 1},
      sophistication: 1.5,
      yield: 2,
      baseQuality: 1.0,
      durationMinutes: 30,
      minKnifeSkills: 10,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'seared_beef',
      name: 'Seared Beef Slice',
      ingredients: {'meat_beef': 1, 'butter': 1, 'salt': 1, 'pepper': 1},
      sophistication: 2.0,
      yield: 2,
      baseQuality: 1.2,
      durationMinutes: 20,
      minKnifeSkills: 10,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'spaghetti_pomodoro',
      name: 'Spaghetti al Pomodoro',
      ingredients: {'sheet_pasta': 1, 'tomato_sauce': 1},
      sophistication: 3.0,
      yield: 3,
      baseQuality: 1.3,
      durationMinutes: 35,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'lasagna_al_forno',
      name: 'Lasagna al Forno',
      ingredients: {'sheet_pasta': 1, 'tomato_sauce': 1, 'seared_beef': 1, 'cheese': 1},
      sophistication: 7.5,
      yield: 6,
      baseQuality: 2.5,
      durationMinutes: 90,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'pasta_genovese',
      name: 'Pasta Genovese',
      ingredients: {'sheet_pasta': 1, 'genovese_sauce': 1},
      sophistication: 6.5,
      yield: 4,
      baseQuality: 2.2,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'pizza_margherita',
      name: 'Pizza Margherita',
      ingredients: {'bread_dough': 1, 'tomato_sauce': 1, 'cheese': 1},
      sophistication: 4.5,
      yield: 4,
      baseQuality: 1.6,
      durationMinutes: 40,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'apple_strudel',
      name: 'Apple Strudel',
      ingredients: {'baked_apple_comp': 1, 'sweet_pastry_dough': 1},
      sophistication: 5.5,
      yield: 8,
      baseQuality: 2.4,
      durationMinutes: 90,
      minKnifeSkills: 30,
      minFireSkills: 35,
    ),
    Recipe(
      id: 'pain_au_chocolat',
      name: 'Pain au Chocolat',
      ingredients: {'sweet_pastry_dough': 1, 'chocolate': 1},
      sophistication: 5.0,
      yield: 4,
      baseQuality: 2.0,
      durationMinutes: 60,
      minKnifeSkills: 15,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'gourmet_cheeseburger',
      name: 'Gourmet Cheeseburger',
      ingredients: {'staple_bread': 1, 'seared_beef': 1, 'cheese': 1},
      sophistication: 4.8,
      yield: 2,
      baseQuality: 1.8,
      durationMinutes: 40,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'cacio_e_pepe',
      name: 'Cacio e Pepe',
      ingredients: {'sheet_pasta': 1, 'cheese': 1, 'pepper': 1},
      sophistication: 3.5,
      yield: 2,
      baseQuality: 1.3,
      durationMinutes: 25,
      minKnifeSkills: 10,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'spaghetti_gricia',
      name: 'Spaghetti alla Gricia',
      ingredients: {'sheet_pasta': 1, 'meat_pork': 1, 'cheese': 1, 'pepper': 1},
      sophistication: 4.0,
      yield: 3,
      baseQuality: 1.5,
      durationMinutes: 30,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'spaghetti_amatriciana',
      name: 'Spaghetti all\'Amatriciana',
      ingredients: {'sheet_pasta': 1, 'meat_pork': 1, 'tomato_sauce': 1, 'cheese': 1},
      sophistication: 4.5,
      yield: 3,
      baseQuality: 1.6,
      durationMinutes: 40,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'spiced_warm_cider',
      name: 'Spiced Warm Cider',
      ingredients: {'cider': 1, 'cinnamon': 1, 'sugar': 1},
      sophistication: 3.0,
      yield: 4,
      baseQuality: 1.8,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 15,
    ),

    // Hidden/Special pseudo-recipes
    Recipe(
      id: 'butcher_generic',
      name: 'Butcher Resident or Creature',
      ingredients: {},
      sophistication: 0.0,
      isExperimental: false, // Don't show in discovery
      durationMinutes: 45,
      minKnifeSkills: 20,
    ),
  ];
}
