// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'kitchen_service.dart';

class RecipeCatalogue {
  static final List<Recipe> allRecipes = [
    // --- Starting / Common (Sophistication 0.0 - 1.5) ---
    Recipe(
      id: 'staple_bread',
      name: 'Spelt Bread',
      ingredients: {'flour_spelt': 1, 'salt': 1},
      sophistication: 1.0,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 60,
      minKnifeSkills: 5,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'hard_hardtack',
      name: 'Hardtack',
      ingredients: {'flour': 1, 'salt': 2},
      sophistication: 0.5,
      yield: 5,
      baseQuality: 0.5,
      durationMinutes: 60,
      minKnifeSkills: 0,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'protein_mistery_stew',
      name: 'Stew of Unknown Protein',
      ingredients: {'meat': 1, 'potato': 1, 'salt': 1},
      sophistication: 0.8,
      yield: 4,
      baseQuality: 0.8,
      durationMinutes: 60,
      minKnifeSkills: 10,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'fried_generic_meat',
      name: 'Sizzling Generic Protein',
      ingredients: {'meat': 1, 'pepper': 1},
      sophistication: 0.9,
      yield: 2,
      baseQuality: 0.9,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'boiled_cabbage',
      name: 'Boiled Cabbage',
      ingredients: {'cabbage': 1, 'salt': 1},
      sophistication: 0.6,
      yield: 2,
      baseQuality: 0.7,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'roasted_rat',
      name: 'Roasted Rat on a Stick',
      ingredients: {'meat_rat': 1, 'salt': 1},
      sophistication: 0.2,
      yield: 1,
      baseQuality: 0.3,
      durationMinutes: 20,
      minKnifeSkills: 5,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'porridge',
      name: 'Simple Porridge',
      ingredients: {'grain': 2},
      sophistication: 0.4,
      yield: 3,
      baseQuality: 0.8,
      durationMinutes: 20,
      minKnifeSkills: 0,
      minFireSkills: 5,
    ),
    Recipe(
      id: 'scrambled_eggs',
      name: 'Scrambled Eggs',
      ingredients: {'eggs': 2, 'butter': 1, 'salt': 1},
      sophistication: 1.2,
      yield: 2,
      baseQuality: 1.0,
      durationMinutes: 10,
      minKnifeSkills: 0,
      minFireSkills: 10,
    ),

    // --- Low / Standard (Sophistication 1.5 - 2.5) ---
    Recipe(
      id: 'omelette',
      name: 'Country Omelette',
      ingredients: {'eggs': 2, 'salt': 1},
      sophistication: 1.8,
      yield: 5,
      baseQuality: 1.2,
      durationMinutes: 30,
      minKnifeSkills: 5,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'mashed_potatoes',
      name: 'Mashed Potatoes',
      ingredients: {'potato': 2, 'butter': 1, 'salt': 1},
      sophistication: 1.5,
      yield: 4,
      baseQuality: 1.1,
      durationMinutes: 30,
      minKnifeSkills: 10,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'baked_potato',
      name: 'Baked Potato',
      ingredients: {'potato': 1, 'salt': 1},
      sophistication: 1.2,
      yield: 1,
      baseQuality: 1.0,
      durationMinutes: 45,
      minKnifeSkills: 0,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'bean_stew',
      name: 'Faba & Green Bean Stew',
      ingredients: {'faba_beans': 1, 'green_beans': 1, 'salt': 1},
      sophistication: 2.1,
      yield: 4,
      baseQuality: 1.0,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'roast_chicken',
      name: 'Herbed Roast Chicken',
      ingredients: {'meat_chicken': 1, 'salt': 1, 'pepper': 1},
      sophistication: 2.3,
      yield: 4,
      baseQuality: 1.3,
      durationMinutes: 120,
      minKnifeSkills: 25,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'chicken_soup',
      name: 'Chicken Soup',
      ingredients: {'meat_chicken': 1, 'carrots': 1, 'onion': 1, 'salt': 1},
      sophistication: 2.2,
      yield: 5,
      baseQuality: 1.4,
      durationMinutes: 90,
      minKnifeSkills: 15,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'vegetable_stew',
      name: 'Root Vegetable Stew',
      ingredients: {'potato': 1, 'carrots': 1, 'onion': 1, 'salt': 1},
      sophistication: 1.9,
      yield: 5,
      baseQuality: 1.1,
      durationMinutes: 60,
      minKnifeSkills: 15,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'grilled_fish',
      name: 'Grilled River Fish',
      ingredients: {'fish': 1, 'salt': 1, 'lemon': 1},
      sophistication: 2.0,
      yield: 2,
      baseQuality: 1.3,
      durationMinutes: 20,
      minKnifeSkills: 15,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'pork_chops',
      name: 'Pan-seared Pork Chops',
      ingredients: {'meat_pork': 1, 'salt': 1, 'pepper': 1, 'butter': 1},
      sophistication: 2.4,
      yield: 2,
      baseQuality: 1.4,
      durationMinutes: 25,
      minKnifeSkills: 10,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'sausage_links',
      name: 'Smoked Sausage Links',
      ingredients: {'meat_pork': 1, 'pepper': 1, 'salt': 1, 'paprika': 1},
      sophistication: 2.2,
      yield: 6,
      baseQuality: 1.2,
      durationMinutes: 180,
      minKnifeSkills: 30,
      minFireSkills: 15,
    ),

    // --- Standard / High (Sophistication 2.5 - 3.5) ---
    Recipe(
      id: 'beef_root_stew',
      name: 'Beef & Root Stew',
      ingredients: {'meat_beef': 10, 'potato': 1, 'carrots': 1, 'beets': 1},
      sophistication: 2.6,
      yield: 6,
      baseQuality: 1.4,
      durationMinutes: 150,
      minKnifeSkills: 30,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'durum_pasta',
      name: 'Fresh Durum Pasta',
      ingredients: {'flour_durum': 1, 'eggs': 2},
      sophistication: 2.7,
      yield: 3,
      baseQuality: 1.1,
      durationMinutes: 90,
      minKnifeSkills: 15,
      minFireSkills: 10,
    ),
    Recipe(
      id: 'spaghetti_carbonara',
      name: 'Spaghetti Carbonara',
      ingredients: {'flour_durum': 1, 'eggs': 1, 'cheese': 1, 'meat_pork': 1},
      sophistication: 3.2,
      yield: 3,
      baseQuality: 1.8,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'shepherds_pie',
      name: 'Shepherd\'s Pie',
      ingredients: {'meat_beef': 1, 'carrots': 1, 'onion': 1, 'potato': 1},
      sophistication: 2.8,
      yield: 6,
      baseQuality: 1.6,
      durationMinutes: 90,
      minKnifeSkills: 25,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'potato_dauphinoise',
      name: 'Potato Dauphinoise',
      ingredients: {'potato': 1, 'cream': 1, 'cheese': 1, 'salt': 1},
      sophistication: 3.1,
      yield: 4,
      baseQuality: 1.7,
      durationMinutes: 80,
      minKnifeSkills: 30,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'tartiflette',
      name: 'Tartiflette',
      ingredients: {'cheese': 1, 'potato': 1, 'meat_pork': 1, 'onion': 1},
      sophistication: 3.3,
      yield: 6,
      baseQuality: 1.8,
      durationMinutes: 70,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),
    Recipe(
      id: 'gnocchi',
      name: 'Potato Gnocchi',
      ingredients: {'potato': 1, 'flour': 1, 'salt': 1, 'eggs': 1},
      sophistication: 2.9,
      yield: 4,
      baseQuality: 1.5,
      durationMinutes: 60,
      minKnifeSkills: 25,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'latkes',
      name: 'Potato Latkes',
      ingredients: {'potato': 1, 'onion': 1, 'salt': 1, 'eggs': 1},
      sophistication: 2.7,
      yield: 4,
      baseQuality: 1.4,
      durationMinutes: 40,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'mushroom_risotto',
      name: 'Mushroom Risotto',
      ingredients: {'rice': 1, 'mushrooms': 1, 'onion': 1, 'cheese': 1},
      sophistication: 3.4,
      yield: 4,
      baseQuality: 1.9,
      durationMinutes: 50,
      minKnifeSkills: 25,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'stuffed_peppers',
      name: 'Stuffed Peppers',
      ingredients: {'peppers': 1, 'meat_beef': 1, 'rice': 1, 'onion': 1},
      sophistication: 2.9,
      yield: 4,
      baseQuality: 1.6,
      durationMinutes: 65,
      minKnifeSkills: 20,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'fish_and_chips',
      name: 'Fish and Chips',
      ingredients: {'fish': 1, 'potato': 1, 'flour': 1, 'salt': 1},
      sophistication: 2.6,
      yield: 3,
      baseQuality: 1.5,
      durationMinutes: 45,
      minKnifeSkills: 20,
      minFireSkills: 25,
    ),

    // --- High Sophistication (3.5 - 4.5) ---
    Recipe(
      id: 'fondant_potatoes',
      name: 'Fondant Potatoes',
      ingredients: {'potato': 1, 'butter': 1, 'meat': 1, 'garlic': 1},
      sophistication: 3.8,
      yield: 4,
      baseQuality: 2.2,
      durationMinutes: 50,
      minKnifeSkills: 35,
      minFireSkills: 40,
    ),
    Recipe(
      id: 'beef_bourguignon',
      name: 'Beef Bourguignon',
      ingredients: {'meat_beef': 1, 'wine': 1, 'mushrooms': 1, 'onion': 1},
      sophistication: 4.2,
      yield: 6,
      baseQuality: 2.5,
      durationMinutes: 240,
      minKnifeSkills: 30,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'coq_au_vin',
      name: 'Coq au Vin',
      ingredients: {'meat_chicken': 1, 'wine': 1, 'mushrooms': 1, 'onion': 1},
      sophistication: 4.1,
      yield: 5,
      baseQuality: 2.4,
      durationMinutes: 180,
      minKnifeSkills: 25,
      minFireSkills: 40,
    ),
    Recipe(
      id: 'chocolate_delight',
      name: 'Chocolate Ganache',
      ingredients: {'chocolate': 1, 'sugar': 1, 'milk': 1},
      sophistication: 3.9,
      yield: 2,
      baseQuality: 2.5,
      durationMinutes: 60,
      minKnifeSkills: 20,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'morning_ritual',
      name: 'Coffee Blend',
      ingredients: {'coffee': 1, 'sugar': 1},
      sophistication: 3.5,
      yield: 1,
      baseQuality: 1.8,
      durationMinutes: 10,
      minKnifeSkills: 5,
      minFireSkills: 15,
    ),
    Recipe(
      id: 'roast_duck',
      name: 'Crispy Roast Duck',
      ingredients: {'meat_duck': 1, 'salt': 1, 'honey': 1, 'pepper': 1},
      sophistication: 4.0,
      yield: 4,
      baseQuality: 2.3,
      durationMinutes: 150,
      minKnifeSkills: 30,
      minFireSkills: 35,
    ),
    Recipe(
      id: 'rack_of_lamb',
      name: 'Herb-Crusted Rack of Lamb',
      ingredients: {'meat_lamb': 1, 'pepper': 1, 'garlic': 1, 'mustard': 1},
      sophistication: 4.3,
      yield: 4,
      baseQuality: 2.6,
      durationMinutes: 45,
      minKnifeSkills: 35,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'scallop_ceviche',
      name: 'Scallop Ceviche',
      ingredients: {'scallops': 1, 'lemon': 1, 'onion': 1, 'salt': 1},
      sophistication: 3.7,
      yield: 2,
      baseQuality: 2.1,
      durationMinutes: 20,
      minKnifeSkills: 40,
      minFireSkills: 0,
    ),

    // --- Exquisite (4.5 - 5.0) ---
    Recipe(
      id: 'potatoes_aligot',
      name: 'Potatoes Aligot',
      ingredients: {'potato': 1, 'butter': 2, 'cheese': 1},
      sophistication: 4.6,
      yield: 4,
      baseQuality: 3.0,
      durationMinutes: 90,
      minKnifeSkills: 30,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'beef_wellington',
      name: 'Beef Wellington',
      ingredients: {'meat_beef': 1, 'flour': 1, 'mushrooms': 1, 'wine': 1},
      sophistication: 4.9,
      yield: 5,
      baseQuality: 3.5,
      durationMinutes: 180,
      minKnifeSkills: 50,
      minFireSkills: 50,
    ),
    Recipe(
      id: 'truffle_pasta',
      name: 'Fresh Truffle Pasta',
      ingredients: {'flour_durum': 1, 'eggs': 1, 'truffles': 1, 'cheese': 1},
      sophistication: 4.8,
      yield: 3,
      baseQuality: 3.3,
      durationMinutes: 45,
      minKnifeSkills: 40,
      minFireSkills: 30,
    ),
    Recipe(
      id: 'lobster_thermidor',
      name: 'Lobster Thermidor',
      ingredients: {'lobster': 1, 'cream': 1, 'cheese': 1, 'wine': 1},
      sophistication: 5.0,
      yield: 2,
      baseQuality: 3.8,
      durationMinutes: 90,
      minKnifeSkills: 45,
      minFireSkills: 50,
    ),
    Recipe(
      id: 'macaron_tower',
      name: 'Tower of Macarons',
      ingredients: {'almond_flour': 1, 'sugar': 1, 'eggs': 1, 'chocolate': 1},
      sophistication: 4.7,
      yield: 10,
      baseQuality: 3.2,
      durationMinutes: 120,
      minKnifeSkills: 40,
      minFireSkills: 45,
    ),
    Recipe(
      id: 'foie_gras_terrine',
      name: 'Foie Gras Terrine',
      ingredients: {'foie_gras': 1, 'wine': 1, 'salt': 1, 'pepper': 1},
      sophistication: 4.6,
      yield: 4,
      baseQuality: 3.1,
      durationMinutes: 300,
      minKnifeSkills: 35,
      minFireSkills: 20,
    ),
    Recipe(
      id: 'caviar_blinis',
      name: 'Caviar Blinis',
      ingredients: {'caviar': 1, 'flour': 1, 'eggs': 1, 'cream': 1},
      sophistication: 4.5,
      yield: 4,
      baseQuality: 2.9,
      durationMinutes: 40,
      minKnifeSkills: 20,
      minFireSkills: 30,
    ),

    // Hidden/Special pseudo-recipes
    Recipe(
      id: 'butcher_generic',
      name: 'Butcher Resident or Creature',
      ingredients: {},
      sophistication: 0.0,
      isExperimental: true, // Don't show in discovery
      durationMinutes: 45,
      minKnifeSkills: 20,
    ),
  ];
}
